Zenika/zenika-formation-framework

- Dockerfile
The idea is to push this to a zenika/formations images (using auto-build), so that all other formations can use to define a docker images. (could not re-open #29).
That way, for a new *formation*, it's a really simple ``Dockerfile`` :
```dockerfile
FROM zenika/formations
MAINTAINER John Doe <john.doe@zenika.com>
```
And we could setup an *Automated Build* for it too :wink: .
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Add a Dockerfile 'onbuild'

- Dockerfile
L'idée c'est avoir une image Docker unique, avec le framework pré-installé, qui permet de lancer toutes les formations Zenika. 
J'ai donc modifié le Dockerfile de la façon suivante :
* Il se base base sur l'image officielle [node:0.10](https://registry.hub.docker.com/_/node/)
* L'application formation-framework est installée sous `/data/node_modules/zenika-formation-framework`
* `grunt` et `grunt-cli` sont également installés
* La commande par défault est `grunt`
Une fois que cette PR sera mergée on pourra créer un *automated build* de l'image `zenika/formation-framework` sur DockeHub et cette image permettra de lancer toutes les formations Zenika en utilisant la commande :
``` sh
docker run -d -P \
-v $PWD/Slides:/data/Slides \
-v $PWD/Gruntfile.js:/data/Gruntfile.js \
-v …
```
> Dockerfile Updates

- summary.html
Dans la *page de garde* `summary.html` le titre de la formation étatait hardcodé. 
J'ai remplacé `Formation AngularJs`  avec le placeholder `FORMATION_DESCRIPTION` ;-)
> Fix the title in summary.html

- Gruntfile.js
- summary.html
*NOTE: Cette PR est liée à la pull request [#41 de Formation--Modele](https://github.com/Zenika/Formation--Modele/pull/41)*  
**Le Besoin**
Afficher la page de garde, non seulement sur app engine, mais aussi en local, en utilisant l'image Docker `zenika/formation-framework`. 
**Les Problèmes**
* Les fichiers `index.html` et `summary.html` doivent être renommés en `slides.html` et `index.html` respectivement. Et cela doit se faire après avoir lancé `grunt sed`. Mais avant de lancer `grunt displaySlides` :smile:. Et même si le task `copy:dist` fait déjà le job de renaming, ce task fait beaucoup de choses (ça prend du temps) et les fichiers sont copiés dans le repertoire dist (ce qui pose problème pour le live reloading).
* La page de garde `summary.html` a des liens vers les PDF. Ces PDF se …
> Docker image improvements

- Dockerfile
- Gruntfile.js
- README.md
- index.html
- package.json
- reveal/run.js
Deux éléments dans cette PR :
- Pour que les formations puissent utiliser les npm scripts plutôt que d'avoir à installer Grunt, le framework ramènent maintenant `grunt` et `grunt-cli` comme dépendances.
- Les formations n'ont plus à dépendre de `grunt` et peuvent utiliser la commande `grunt` dans leurs npm scripts.
- Suite à cette PR, il faudrait tagguer une nouvelle version afin que les formations puissent avoir accès à cette feature. Je ferais un PR pour upgrader le modèle dès que ce sera fait.
- Pour que le framework soit compatible avec npm 3, il ne suppose plus que les dépendances sont installées en arborescence (npm 3 installe tout à plat).
- J'en ai profité pour nettoyer un peu le code qui tourne autour des paths dans le Gruntfile
- J'en ai profité pour éliminer le mélange …
> npm scripts and npm 3 support

- .editorconfig
- CHANGELOG.md
- Gruntfile.js
- gulpfile.js
- index.html
- package.json
- reveal/plugins/print-pdf/print-pdf.js
- reveal/promise.js
- reveal/run.js
- reveal/setimmediate.js
- reveal/theme-zenika/pdf.css
- reveal/theme-zenika/theme.css
- feat: ouverture forcée dans Chrome 	
- feat: ajout d'un mode debug pour les PDF
- feat: screenshot & HTML sauvegardé en mode debug des PDF avec PhantomJS
- feat: ajout de logs avec timestamp
- feat: montée de la version en 0.4.5 + change log
- fix: génération de PDF dans le navigateur
- fix: génération de PDF avec PhantomJS
- fix: problème avec PhantomJS 1.x qui ne gère pas les `Promise`
- fix: ajout d'un polyfill qui ne s'active que si les `Promise` n'existe pas dans le browser
- fix: problème avec PhantomJS et XMLHttpRequest
- fix: augmentation du temps d'attente avant la création du PDF (1000ms -> 10000ms)
Tests effectués avec NPM2 :
- ouverture de la formation avec `grunt`
- génération de PDF utilisant PhantomJS avec `grunt generateSlidesPDF`
Tests effectués avec NPM3 :
- ouverture …
> PDF, Chrome et debug

- Dockerfile
- cette version version reste avec npm 2 donc pas de problème de build
- cette version enlève l'erreur :
- `warning: possible EventEmitter memory leak detected`
- c'est une version LTS donc plutôt positive pour la CI
> chore: montée de version de Node dans le Dockerfile

- Gruntfile.js
- index.html
Cf #77. C'est pas particulièrement beau ou performant, mais je pense que c'est mieux que 2 builds différents.
J'ai aussi modifié les chemins qu'expose le serveur pour que `index.html` n'est pas à supporter des chemins différents pour npm 2 et 3.
> feat: gruntfile compatible avec npm 2 et 3

- reveal/theme-zenika/theme.css
En version 49 de firefox et 53.0.2785.143 de chrome, lors du passage en fullscreen de la présentation, le fond d'écran et des slides passent en noir.
Cette PR corrige ces pb en attendant la resynchro avec une version plus récente de reveal.js
cf : https://github.com/hakimel/reveal.js/issues/1386#issuecomment-225379825
> Correction fond lors du passage en fullscreen

- reveal/theme-zenika/pdf.css
Lors d'une impression, 1 page sur 2 est blanche : 
En diminuant la hauteur de la section, le pb est corrigé : 
Je me doute bien qu'il faut trouver d'où vient ce foutu pixel d'écart (une page fait 210 mm, je fixe la taille de la section à 209 mm au lieu de 210mm) mais je ne trouve pas mieux.
> Lors d'une impression, 1 page sur 2 est blanche

- deploy.js
- gcloud-deploy.sh
- gcloud-install.sh
- package.json
Cette PR remplace le script `gcloud-deploy.sh` par un équivalent en JS, ce qui permet au framework de l'exposer en tant qu'exécutable aux formations qui dépendent de lui. Elle peuvent alors l'utiliser dans leurs scripts npm. Ceci permet aux formations de ne plus avoir à appeler `gcloud-deploy.sh` manuellement, ce qui pose des problèmes de permissions (cf #130).
> chore(#130): deploy bin script

- Dockerfile
There is now an official apline-flavored node docker image.
> fix(#122): Base Dockerfile on a node-alpine image

- reveal/theme-zenika/pdf.css
- reveal/theme-zenika/theme.css
[Zenika-Formation-formation-angularjs-Slides.pdf](https://github.com/Zenika/zenika-formation-framework/files/790903/Zenika-Formation-formation-angularjs-Slides.pdf)
[Zenika-Formation-Git-Slides.pdf](https://github.com/Zenika/zenika-formation-framework/files/790904/Zenika-Formation-Git-Slides.pdf)
C'est moins clean qu'avec du flex, mais ça marche avec les pdf
> Centrer le titre sur la page d'accueil

- deploy.js
`config.deploy.name` is longer used for deployment. Was replaced with `name`.
> chore(deploy): fixed displayed url when deploying

- Dockerfile
- Gruntfile.js
- circle.yml
- package-lock.json
- package.json
- pdf/generate-pdf-with-chrome.js
- reveal/theme-zenika/theme.css
https://github.com/GoogleChrome/puppeteer
This enables us to use the current Node.js Docker image to generate PDFs using Chrome, because puppeteer downloads Chrome instead of expecting the system to have one.
> Use puppeteer for Chrome control

- reveal/theme-zenika/theme.css
Exemple : https://formation-go-dot-zen-formations.appspot.com/slides.html#/2/10
> Sous chrome 61 les numéros de TP ne sont plus visible

- .gitignore
Ajouter le dossier `.vscode` au gitignore pour permettre de configurer sont éditeur sans tout polluer.
> :wrench: Update gitignore for VSCode

- Gruntfile.js
After a talk with @ncuillery and @T3kstiil3 about trainings materials, here is a POC if we want to make our materials specific for an agency / country / ...
We just need, for both slides and PW, create a specific folder for the agency (let say `ca` for canada), and use the new locale CLI parameter. If for exanple, I want to create a specific version of the PW file `PW1.md`, we juste need to create a `/ca/PW1.md` file. 
Thanks to this first architecture, we can make a complete chapter / PW specific to an agency. 
Next step, have a look if it is possible to make this behavior possible for specific slides (and not the complete chapter)
I also updated the repo `Formation--Modele`  https://github.com/Zenika/Formation--Modele/pull/136
What do you think ?
> feat: give the possibility to have materials specific to a country

- Gruntfile.js
:bug: Use 2017 theme by default for running (`npm start`/`grunt`) and pdf generation (`npm start pdf`/`grunt pdf`)
:sparkles: Add an `--old-theme` parameter for both commands to use the old theme
> 💄 use theme 2017 by default

- Dockerfile
- pdf/noto-conf/noto-color.conf
Hey 👋 
A little PR to add emoji rendering in pdf : 
before : 
after:
Emojis are a little glitchy... I think this is not a problem since the framework will soon be in EOL but if you know why this happening, I will be happy to amend this PR 👍
> ✨ add font-noto-emoji and config
