.editorconfig

- avoir un style homogène entre les devs

feat(*): ajout de la configuration EditorConfig

---

reveal/run.js

Utilisation de la roulette pour changer de slides.

feat(slides) activation de la navigation avec la souris.

---

Gruntfile.js
index.html
package.json
reveal/run.js
reveal/theme-zenika/code.css

Upgrade to reveal 3.1

---

CHANGELOG.md
package.json

0.4.xx est en reveal v2
0.5.xx est en reveal v3

Version 0.5.0: passage à reveal v3

---

CHANGELOG.md
package.json

feat: version 0.4.2

---

gcloud-install.sh

fix gcloud version to prevent beta changes

---

Gruntfile.js
deploy.js
package.json

This is trying to fix this failure: https://circleci.com/gh/Zenika/Formation--Modele/77
Reference: https://github.com/GoogleCloudPlatform/continuous-deployment-circle/blob/master/circle.yml#L31
Issue: #130 
Le commit important c'est celui-là : https://github.com/Zenika/zenika-formation-framework/pull/132/commits/79d733afb99f7ba3c5122b1df0dab5b8e10d6975. https://github.com/Zenika/zenika-formation-framework/pull/132/commits/bfb90486309aea2c5e1565e614d99da4b27a05fa et https://github.com/Zenika/zenika-formation-framework/pull/132/commits/3bfabd40d6e7dbac302d95d632b47484b9c3de4e sont des commits qui aurait du être dans #131. Le reste sont des commits générés par npm et sont revertés.
Calling @jlandure to review. :)

chore: update gcloud sdk before deploy

---

Gruntfile.js

Plusieurs clé identique, donc celle-ci était perdu

[Closes #154] replace FORMATION_NAME

---

README.md
ic.js
package.json
rebuild-all.js

Closes #165.
Potential problem: I don't if the project followed depend on the user connecting to the API or not.

chore(#165): rebuild all projects after publish

---

reveal/run.js

Closes #125.
Press W to cycle through different aspect ratios: ~4:3 (default), 16:9, 16:10.
@gmembre-zenika As you are the one who opened the issue, could you review and test?
@moreau-nicolas I selected you as a reviewer so you could check that your remote mode still works after this refactoring. Could you review too?

feat(#125): support for wide screens

---

reveal/run.js

fix(#176) fix default lang for prism

---

Gruntfile.js
reveal/run.js

chore(#176): package prism

---

.eslintignore
.eslintrc.json
Gruntfile.js
deploy.js
gulpfile.js
ic.js
package.json
rebuild-all.js
reveal/.eslintrc.json
reveal/plugins/zenika-footer/zenika-footer.js
reveal/run.js

:warning: This PR has to wait for #168 because PhantomJS 1.x does not support ES2015.
4 rules were disabled or tweaked because they were too complex to comply with right now. They should be enabled in the future, whenever there is time to work on it.
There is nothing interesting to review here as most modifications were made by eslint autofix. Please avoid any fruitless debate on the style guide choice. It is arbitrary.

style: eslint with airbnb config

---

reveal/run.js

fix: prism is not defined

---

README.md

Should be in English. Will redo.

docs(readme): faire une release

---

Gruntfile.js
README.md

feat #189 - Add args to specify folder location of slides and labs

feat #189 - Add args to specify folder location of slides and labs

---

reveal/theme-zenika/theme.css

Demander dans https://github.com/Zenika/formation-go/issues/60

Ajout de nouvelles classes CSS page-tpxx

---

Gruntfile.js
package-lock.json
package.json
pdf/generate-pdf-with-chrome.js
reveal/theme-zenika/code.css

:wrench: labs pdf generation with Chrome

---

reveal/theme-zenika/theme.css

feat #204 - Change TP to Lab in generated slides

---

CHANGELOG.md

See https://github.com/Zenika/Formation--Modele/issues/127 and https://github.com/Zenika/Formation--Modele/pulls/128.

:memo: fix migration procedure to v3

---

reveal/run.js

Add MathAjax module to display math equations

---

reveal/theme-zenika/theme.css

the version is not dynamic anymore since commit d013b54

reinstate dynamic VERSION in pdf docs

---

styleCahierExercice.css

Wrap code in labs

---

Gruntfile.js
README.md
reveal/run.js

What if the user of the framework was able to override the Reveal option, and add extra plugins for example ? Like this beautiful chart :D . Now it is possible with this PR.

Override reveal options

---

app.yaml

#246 Correct the generate labs

:rocket: Deploy the labs in html
